[package]
name = "bongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18"
crossterm = "0.23"
unicode-width = "0.1.4"

[dependencies.mongodb]
version = "2.2.0"
features = ["tokio-sync"]
